apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # This MUST match the selector above
    spec:
      containers:
      - name: frontend
        image: vinithaaws/my-app:88e39db7248b9a2f0a30e0141ffc7e56c5a6255a
        ports:
        - containerPort: 3000
  strategy:
    canary:
      stableService: frontend
      canaryService: frontend-canary
    analysis:
      templates:
        - templateName: success-rate-check
      trafficRouting:
        nginx:
          stableIngress: emp-ingress
      steps:
      - setWeight: 20
        # If you want it to wait for you to click "Promote" in ArgoCD UI:
      - pause: {} 
      - setWeight: 50
      - pause: { duration: 2m } # Or wait automatically for 2 minutes
      - setWeight: 100