apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /employee
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend   # FIXED
            port:
              number: 3000