name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./employeemanagement-frontend # This defines where your source code is
          file: ./employeemanagement-frontend/Dockerfile # This points to the Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

      - name: Update GitOps Repo
        run: |
          git config --global user.email "nayakvnitha413@gmail.com"
          git config --global user.name "Vinitha-Nayak"

          # This finds the file regardless of where it is and updates it
          FILE_PATH=$(find . -name "frontend-rollout.yaml")
          echo "Updating file at: $FILE_PATH"

          # Updating the manifest with the new Docker Hub image path
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}|g" "$FILE_PATH"         
          
          git add "$FILE_PATH"
          git commit -m "Bump image to ${{ github.sha }}"
          git push
